In [1]:
import numpy as np
from scipy.stats import ttest_1samp, ttest_ind, mannwhitneyu, levene, shapiro,bartlett,wilcoxon
from statsmodels.stats.power import ttest_power
import pandas as pd
#import scipy.stats as stats
from scipy.stats import chisquare,chi2_contingency
%matplotlib inline

In [ ]:
#load the migrain data and check whether there is a dependency exist between type of migrain with
#respect to male female

In [2]:
migrain = pd.read_csv('Migraine.csv',index_col=0)

In [4]:
migrain.columns

Index(['id', 'time', 'dos', 'hatype', 'age', 'airq', 'medication', 'headache',
       'Gender'],
      dtype='object')

In [5]:
migrain.head()

id  time  dos hatype  age  airq  medication headache  Gender
1   1   -11  753   Aura   30   9.0  continuing      yes  female
2   1   -10  754   Aura   30   7.0  continuing      yes  female
3   1    -9  755   Aura   30  10.0  continuing      yes  female
4   1    -8  756   Aura   30  13.0  continuing      yes  female
5   1    -7  757   Aura   30  18.0  continuing      yes  female

In [6]:
migrain['hatype'].value_counts()

No Aura    1985
Aura       1710
Mixed       457
Name: hatype, dtype: int64

In [15]:
chisquare(migrain['hatype'].value_counts())

Power_divergenceResult(statistic=958.6748554913295, pvalue=6.705021277393725e-209)

In [16]:
migrain['Gender'].value_counts()

female    3545
male       607
Name: Gender, dtype: int64

In [17]:
chisquare(migrain['Gender'].value_counts())

Power_divergenceResult(statistic=2078.960500963391, pvalue=0.0)

In [9]:
CT=pd.crosstab(migrain['Gender'],migrain['hatype'])
CT

hatype  Aura  Mixed  No Aura
Gender                      
female  1593    291     1661
male     117    166      324

In [11]:
ch_val,P_val,nrow,EC=chi2_contingency(CT)

In [12]:
print(ch_val)

259.94962922327386


In [13]:
print(P_val)

3.569893234435195e-57


In [14]:
print(EC)

[[1460.00722543  390.18906551 1694.80370906]
 [ 249.99277457   66.81093449  290.19629094]]


In [ ]:
#inference: as p-val <0.05 ,we reject the H0 and there is a significant difference between type and gender

In [20]:
1593/3545,291/3545,1661/3545

(0.44936530324400564, 0.08208744710860366, 0.4685472496473907)

In [19]:
117/607,166/607,324/607

(0.1927512355848435, 0.27347611202635913, 0.5337726523887973)

In [ ]:
# Inference:
# Males are highly sensitive to mixed type of migrain when compared to female
# female are higly sensitive to Aura Type of migrain when compared to male
#

In [21]:
fair = pd.read_csv('fair_pay_data.csv',index_col=0)

In [22]:
fair.head()

department        salary new_hire job_level
employee_id                                              
1                  Sales  103263.63550       No  Salaried
2            Engineering   80708.64104       No    Hourly
4            Engineering   60737.04786      Yes    Hourly
5            Engineering   99116.32328      Yes  Salaried
7            Engineering   51021.64386       No    Hourly

In [24]:
fair.columns

Index(['department', 'salary', 'new_hire', 'job_level'], dtype='object')

In [25]:
fair['job_level'].value_counts()

Hourly      1039
Salaried     326
Manager      105
Name: job_level, dtype: int64

In [27]:
fair['department'].value_counts()

Engineering    961
Sales          446
Finance         63
Name: department, dtype: int64

In [28]:
chisquare(fair['job_level'].value_counts())

Power_divergenceResult(statistic=972.4938775510204, pvalue=6.693259259105296e-212)

In [29]:
chisquare(fair['department'].value_counts())

Power_divergenceResult(statistic=828.7877551020408, pvalue=1.074052833315366e-180)

In [32]:
CT=pd.crosstab(fair['job_level'],fair['department'])
CT

department  Engineering  Finance  Sales
job_level                              
Hourly              688       41    310
Manager              66        6     33
Salaried            207       16    103

In [34]:
chi2_contingency(CT)

(1.7618006349813817,
 0.7794632298921784,
 4,
 array([[679.23741497,  44.52857143, 315.23401361],
        [ 68.64285714,   4.5       ,  31.85714286],
        [213.11972789,  13.97142857,  98.90884354]]))

In [ ]:
print