In [6]:
410/1000,340/1000,250/1000

(0.41, 0.34, 0.25)

In [7]:
95/250,85/250,70/250

(0.38, 0.34, 0.28)

In [10]:
(505*1000)/1250,(425*1000)/1250,(320*1000)/1250

(404.0, 340.0, 256.0)

In [11]:
(505*250)/1250,(425*250)/1250,(320*250)/1250

(101.0, 85.0, 64.0)

In [26]:
import numpy as np
from scipy.stats import ttest_1samp, ttest_ind, mannwhitneyu, levene, shapiro,bartlett,wilcoxon
from statsmodels.stats.power import ttest_power
import pandas as pd
#import scipy.stats as stats
from scipy.stats import chisquare,chi2_contingency
%matplotlib inline

In [29]:
#Example in register
obs= np.array([410,340,250,95,85,70])

In [15]:
obs

array([410, 340, 250,  95,  85,  70])

In [30]:
exp= np.array([404,340,256,101,85,64])

In [20]:
chi_data=(((obs-exp)**2)/exp).sum()
print(chi_data)

1.1486695544554455


In [34]:
#by using built in library
#represent your cross tab (observed count)
CT=pd.DataFrame(np.array([[410,340,250],[95,85,70]])) #Creating data frame
CT.columns=['Healthy','Mild','severe'] #naming the column
CT.index=['SC1','SC2'] #naming the index
CT

Healthy  Mild  severe
SC1      410   340     250
SC2       95    85      70

In [36]:
ch_val,P_val,nrow,EC=chi2_contingency(CT)  #finding chi square test chi data values and expected count

In [37]:
print(ch_val)

1.1486695544554455


In [38]:
print(P_val)

0.5630793174318253


In [39]:
print(EC)

[[404. 340. 256.]
 [101.  85.  64.]]


In [ ]:
# Inference : p-val >.05,which implies,we fail to reject the H0: proportion of samples across the 
#three groups (Healthy,Mild,& severe) is same

In [45]:
hr = pd.read_table('HR (1).txt',index_col=0)

In [47]:
hr.head()

Attrition  Age  BusinessTravel  DailyRate  Department  \
Individual                                                          
Ind1              Yes   41               1       1102           1   
Ind2               No   49               2        279           2   
Ind3              Yes   37               1       1373           2   
Ind4               No   33               2       1392           2   
Ind5               No   27               1        591           2   

             DistanceFromHome  Education  EducationField  EmployeeCount  \
Individual                                                                
Ind1                        1          2               1              1   
Ind2                        8          1               1              1   
Ind3                        2          2               6              1   
Ind4                        3          4               1              1   
Ind5                        2          1               2              1   

             EmployeeNumber          ...           RelationshipSatisfaction  \
Individual                           ...                                      
Ind1                      1          ...                                  1   
Ind2                      2          ...                                  4   
Ind3                      4          ...                                  2   
Ind4                      5          ...                                  3   
Ind5                      7          ...                                  4   

             StandardHours  StockOptionLevel  TotalWorkingYears  \
Individual                                                        
Ind1                    80                 0                  8   
Ind2                    80                 1                 10   
Ind3                    80                 0                  7   
Ind4                    80                 0                  8   
Ind5                    80                 1                  6   

             TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
Individual                                                            
Ind1                             0                1               6   
Ind2                             3                3              10   
Ind3                             3                3               0   
Ind4                             3                3               8   
Ind5                             3                3               2   

             YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
Individual                                                                      
Ind1                          4                        0                     5  
Ind2                          7                        1                     7  
Ind3                          0                        0                     0  
Ind4                          7                        3                     0  
Ind5                          2                        2                     2  

[5 rows x 34 columns]

In [48]:
hr.shape

(1470, 34)

In [55]:
hr['Department'].value_counts()

2    961
1    446
3     63
Name: Department, dtype: int64

In [50]:
CT_hr=pd.crosstab(hr['Attrition'],hr['Department'])
CT_hr

Department    1    2   3
Attrition               
No          354  828  51
Yes          92  133  12

In [51]:
ch_val,P_val,nrow,EC=chi2_contingency(CT_hr)

In [52]:
print(ch_val)

10.79600732241067


In [53]:
print(P_val)

0.004525606574479633


In [54]:
print(EC)

[[374.09387755 806.06326531  52.84285714]
 [ 71.90612245 154.93673469  10.15714286]]


In [ ]:
#inference: as p-val <.05 ,we reject the null hypothesis and there is a significant difference between the attrition of three 
#departments

In [60]:
# to check the proportion of departments 1 dimensional
# if you have to check one categorical variable u should apply 1 dimensional chisquare
chisquare(hr['Department'].value_counts())

Power_divergenceResult(statistic=828.7877551020408, pvalue=1.074052833315366e-180)

In [56]:
#building function for calculating z test
def twosampz(x1,x2,n1,n2):
    p1=x1/n1
    p2=x2/n2
    pp=(x1+x2)/(n1+n2)
    zdata= (p1-p2)/np.sqrt((pp*(1-pp)*((1/n1)+(1/n2))))
    pval=2*(1-stats.norm.cdf(abs(zdata)))
    return round(zdata,3),round(pval,4)

In [58]:
n1= CT_hr.iloc[:,0].sum()
n2= CT_hr.iloc[:,1].sum()
x1= CT_hr.iloc[1,0]
x2= CT_hr.iloc[1,1]