In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import scipy.stats as stats 
#import linear regression machine learning library
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as smf

In [2]:
A=pd.DataFrame({'exp':[2.5,3.0,5.7,4.8,7.0,12.0,8.0],'G':[1,0,1,0,0,1,0],'sal':[6500,8000,4000,12000,10000,15000,6000]})

In [3]:
A

exp  G    sal
0   2.5  1   6500
1   3.0  0   8000
2   5.7  1   4000
3   4.8  0  12000
4   7.0  0  10000
5  12.0  1  15000
6   8.0  0   6000

In [5]:
x=A[['exp','G']]
y=A[['sal']]

In [6]:
m1=LinearRegression()
m1.fit(x,y)
y1_predict=m1.predict(x)
y1_predict

array([[ 5640.4109589 ],
       [ 7176.16761946],
       [ 7801.99007658],
       [ 8392.05587315],
       [ 9878.14151656],
       [12057.59896451],
       [10553.63499083]])

In [7]:
B=pd.DataFrame({'exp':[2.5,3.0,5.7,4.8,7.0,12.0,8.0],'G':[0,1,0,1,1,0,1],'sal':[6500,8000,4000,12000,10000,15000,6000]})
B

exp  G    sal
0   2.5  0   6500
1   3.0  1   8000
2   5.7  0   4000
3   4.8  1  12000
4   7.0  1  10000
5  12.0  0  15000
6   8.0  1   6000

In [8]:
x1=A[['exp','G']]
y1=A[['sal']]

In [9]:
m1=LinearRegression()
m1.fit(x1,y1)
y2_predict=m1.predict(x1)
y2_predict

array([[ 5640.4109589 ],
       [ 7176.16761946],
       [ 7801.99007658],
       [ 8392.05587315],
       [ 9878.14151656],
       [12057.59896451],
       [10553.63499083]])

In [46]:
a_1=A[['exp','G']]
b_1=A[['sal']]

In [47]:
new_col=A['exp']*A['G']
new_col
a=pd.concat([a_1,new_col],axis=1)

In [48]:
a.columns=['exp','g','exp:g']
a

exp  g  exp:g
0   2.5  1    2.5
1   3.0  0    0.0
2   5.7  1    5.7
3   4.8  0    0.0
4   7.0  0    0.0
5  12.0  1   12.0
6   8.0  0    0.0

In [53]:
m3=LinearRegression()
m3.fit(a_1,b_1)
y3_predict=m3.predict(a_1)
y3_predict

array([[ 5640.4109589 ],
       [ 7176.16761946],
       [ 7801.99007658],
       [ 8392.05587315],
       [ 9878.14151656],
       [12057.59896451],
       [10553.63499083]])

In [41]:
c=B[['exp','G']]
d=B[['sal']]

In [42]:
new_col1=B['exp']*B['G']
new_col1
c1=pd.concat([c,new_col1],axis=1)

In [43]:
c1.columns=['exp','g','exp:g']
c1

exp  g  exp:g
0   2.5  0    0.0
1   3.0  1    3.0
2   5.7  0    0.0
3   4.8  1    4.8
4   7.0  1    7.0
5  12.0  0    0.0
6   8.0  1    8.0

In [45]:
m4=LinearRegression()
m4.fit(c,d)
y4_predict=m3.predict(c)
y4_predict

array([[ 5640.4109589 ],
       [ 7176.16761946],
       [ 7801.99007658],
       [ 8392.05587315],
       [ 9878.14151656],
       [12057.59896451],
       [10553.63499083]])