In [27]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import scipy.stats as stats 
#import linear regression machine learning library
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as smf
#pckage to split data into train and test
from sklearn.model_selection import train_test_split
# polynomial feature
from sklearn.preprocessing import PolynomialFeatures
# calculating confusion matricss
from sklearn import metrics
#for labeling
from sklearn import preprocessing
#for roc and auc curve
from sklearn.metrics import roc_curve, auc
#libraries for decision tree
from sklearn.externals.six import StringIO
from IPython.display import Image   #to view the image of the tree
from sklearn.tree import export_graphviz
import pydotplus
# for clustring
from sklearn.preprocessing import scale
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import linkage,dendrogram,cut_tree
# for 3d plotting
from mpl_toolkits.mplot3d import Axes3D
from sklearn.linear_model import LogisticRegression
# for ensemble
from sklearn.ensemble import RandomForestClassifier
# cross Validation
from sklearn.cross_validation import cross_val_score

In [6]:
iris = pd.read_csv('iris.csv',names=['SepailL','SepalW','PetalL','PetalW','Class'])

In [7]:
iris.head()

SepailL  SepalW  PetalL  PetalW        Class
0      5.1     3.5     1.4     0.2  Iris-setosa
1      4.9     3.0     1.4     0.2  Iris-setosa
2      4.7     3.2     1.3     0.2  Iris-setosa
3      4.6     3.1     1.5     0.2  Iris-setosa
4      5.0     3.6     1.4     0.2  Iris-setosa

In [8]:
le = preprocessing.LabelEncoder()
le.fit(iris['Class'])
iris['Class']=le.transform(iris['Class'])
iris.head()

SepailL  SepalW  PetalL  PetalW  Class
0      5.1     3.5     1.4     0.2      0
1      4.9     3.0     1.4     0.2      0
2      4.7     3.2     1.3     0.2      0
3      4.6     3.1     1.5     0.2      0
4      5.0     3.6     1.4     0.2      0

In [9]:
iris['Class'].value_counts()

2    50
1    50
0    50
Name: Class, dtype: int64

In [37]:
x=iris[['SepailL','SepalW','PetalL','PetalW']]
y=iris['Class']


In [38]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 123)

In [39]:
# import the classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [40]:
dtree = DecisionTreeClassifier()

In [41]:
model_dtree = dtree.fit(x_train,y_train)

In [42]:
pred_dtree = dtree.predict(x_test)

In [43]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc,classification_report
cm = confusion_matrix(y_test, dtree.predict(x_test))
print("Confusion Matrix \n",cm)
print(classification_report(y_test,pred_dtree))

Confusion Matrix 
 [[16  0  0]
 [ 0  8  0]
 [ 0  3 11]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.73      1.00      0.84         8
          2       1.00      0.79      0.88        14

avg / total       0.94      0.92      0.92        38



In [44]:
# lets run random forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [45]:
model_rf = rf.fit(x_train,y_train)

In [46]:
pred_rf = rf.predict(x_test)

In [47]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc,classification_report
cm = confusion_matrix(y_test, rf.predict(x_test))
print("Confusion Matrix \n",cm)
print(classification_report(y_test,pred_rf))

Confusion Matrix 
 [[16  0  0]
 [ 0  8  0]
 [ 0  3 11]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.73      1.00      0.84         8
          2       1.00      0.79      0.88        14

avg / total       0.94      0.92      0.92        38



In [48]:
# lets apply knn
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [49]:
model_knn = knn.fit(x_train,y_train)

In [50]:
pred_knn = knn.predict(x_test)

In [51]:
metrics.accuracy_score(y_test,pred_knn)

0.9736842105263158

In [52]:
# cross Validation
from sklearn.cross_validation import cross_val_score

In [53]:
scores= cross_val_score(dtree,x,y,scoring='accuracy',cv=10)

In [54]:
print(scores)

[1.         0.93333333 1.         0.93333333 0.93333333 0.86666667
 0.93333333 1.         1.         1.        ]


In [55]:
scores.mean()

0.96

In [56]:
#Applying 10 fold cross validation - Logistic Regression
LR=LogisticRegression()
LR.fit(x,y)
y_pred=LR.predict(x)

In [57]:
scores= cross_val_score(LR,x,y,scoring='accuracy',cv=10)
scores.mean()

0.9533333333333334

In [58]:
# applying 10 fold cross validation - random forest
scores= cross_val_score(rf,x,y,scoring='accuracy',cv=10)
scores.mean()

0.9533333333333334

In [59]:
# applying 10 fold cross validation on knn
scores= cross_val_score(knn,x,y,scoring='accuracy',cv=10)
scores.mean()

0.9666666666666668

In [60]:
# Logistic reg - 0.9533
# Decision tree - 96
# rf - .9533
# knn - .9666

In [62]:
# parameter tuning using grid search - random forest
rf_param = {
    "n_estimators":[200,500],
    "criterion": ["gini","entropy"],
    "max_depth": [4,5,6,7,8],
    "max_features": ["auto","sqrt","log2"],
    "bootstrap":[True,False]
}

In [63]:
# apply grid search
from sklearn.model_selection import GridSearchCV

In [64]:
grid_srch = GridSearchCV(estimator=rf,param_grid=rf_param,cv=5)

In [66]:
cv_grid = grid_srch.fit(x_train,y_train)

In [68]:
grid_srch.best_params_

{'bootstrap': False,
 'criterion': 'entropy',
 'max_depth': 4,
 'max_features': 'auto',
 'n_estimators': 200}

In [80]:
dtree_param = {
    "random_state" : [123],
      "criterion" : ["gini","entropy"],
      "max_depth" : [2,3,4,5,6],
      "max_features": ["auto","sqrt","log2"],
      "splitter": ["best","random"],
      "min_samples_leaf": [10,30,50]
} 
      




In [81]:
tree_srch = GridSearchCV(estimator=dtree,param_grid=dtree_param,cv=5)

In [82]:
cv_grid_tree = tree_srch.fit(x_train,y_train)

In [83]:
tree_srch.best_params_

{'criterion': 'gini',
 'max_depth': 2,
 'max_features': 'auto',
 'min_samples_leaf': 10,
 'random_state': 123,
 'splitter': 'best'}