In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import scipy.stats as stats 
#import linear regression machine learning library
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as smf
#pckage to split data into train and test
from sklearn.model_selection import train_test_split
# polynomial feature
from sklearn.preprocessing import PolynomialFeatures
# calculating confusion matricss
from sklearn import metrics
#for labeling
from sklearn import preprocessing
#for roc and auc curve
from sklearn.metrics import roc_curve, auc
#libraries for decision tree
from sklearn.externals.six import StringIO
from IPython.display import Image   #to view the image of the tree
from sklearn.tree import export_graphviz
import pydotplus
# for clustring
from sklearn.preprocessing import scale
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import linkage,dendrogram,cut_tree
# for 3d plotting
from mpl_toolkits.mplot3d import Axes3D
from sklearn.linear_model import LogisticRegression
# for ensemble
from sklearn.ensemble import RandomForestClassifier
# cross Validation
from sklearn.cross_validation import cross_val_score

C:\Users\AKSHAY\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
C:\Users\AKSHAY\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
 mnist = pd.read_csv('MNIST.csv')

In [3]:
mnist.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [5]:
x= mnist.drop('label',axis=1)
y= mnist['label']

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30,random_state=123)

In [7]:
# import the classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [8]:
dtree = DecisionTreeClassifier()

In [9]:
model_dtree = dtree.fit(x_train,y_train)

In [10]:
pred_dtree = dtree.predict(x_test)

In [11]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc,classification_report
cm = confusion_matrix(y_test, dtree.predict(x_test))
print("Confusion Matrix \n",cm)
print(classification_report(y_test,pred_dtree))

Confusion Matrix 
 [[1105    0   13   15   10   16   28    5   21   16]
 [   1 1336   15   12    3    8    9    7   16    5]
 [  11   13 1013   52   22   19   20   25   53   17]
 [  14   11   32 1022   14   69    4   24   41   37]
 [   3    9   13    8 1036   21   13   14   24   70]
 [  17    9   17   87   17  943   31   10   30   28]
 [  16   10   26    4   10   38 1129    4   27    7]
 [   5    9   29   17   15   10    4 1166   11   32]
 [   9   17   44   59   30   42   27   11  970   28]
 [   6    4   11   26   50   27    5   51   33 1027]]
             precision    recall  f1-score   support

          0       0.93      0.90      0.91      1229
          1       0.94      0.95      0.94      1412
          2       0.84      0.81      0.82      1245
          3       0.78      0.81      0.80      1268
          4       0.86      0.86      0.86      1211
          5       0.79      0.79      0.79      1189
          6       0.89      0.89      0.89      1271
          7       0.89   

In [12]:
# lets run random forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [13]:
model_rf = rf.fit(x_train,y_train)

In [14]:
pred_rf = rf.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc,classification_report
cm = confusion_matrix(y_test, rf.predict(x_test))
print("Confusion Matrix \n",cm)
print(classification_report(y_test,pred_rf))

Confusion Matrix 
 [[1202    0    4    2    1    2    9    1    8    0]
 [   0 1386    9    2    1    3    0    3    4    4]
 [   8    7 1170   15    5    4    7   12   12    5]
 [   6    3   23 1160    0   35    2   14   18    7]
 [   3    5    5    1 1164    1    4    1    6   21]
 [   7    4    2   51    9 1087   11    1   11    6]
 [   9    4    4    2   11   17 1219    1    4    0]
 [   1    7   29    6   13    3    0 1221    3   15]
 [   6    7   11   30   15   22    5    5 1122   14]
 [  13    2    7   15   47    7    2   23    9 1115]]
             precision    recall  f1-score   support

          0       0.96      0.98      0.97      1229
          1       0.97      0.98      0.98      1412
          2       0.93      0.94      0.93      1245
          3       0.90      0.91      0.91      1268
          4       0.92      0.96      0.94      1211
          5       0.92      0.91      0.92      1189
          6       0.97      0.96      0.96      1271
          7       0.95   

In [16]:
# Apply ensembeles using voting classifier
from sklearn.ensemble import VotingClassifier

In [19]:
voting_model=VotingClassifier([("tree",dtree),("RF",rf)],voting="hard")

In [20]:
voting_tune = voting_model.fit(x_train,y_train)

In [21]:
pred_model = voting_model.predict(x_test)

C:\Users\AKSHAY\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [25]:
cm = confusion_matrix(y_test, pred_model)
print("Confusion Matrix \n",cm)
print(classification_report(y_test,pred_model))

Confusion Matrix 
 [[1218    0    2    2    1    0    5    0    1    0]
 [   2 1386   11    5    2    2    0    1    3    0]
 [  19   22 1164    9    4    7    4   11    4    1]
 [  13   13   52 1161    7   10    0    3    5    4]
 [   6   14   18    4 1144    2    3    4    6   10]
 [  25   11   21  127   19  975    7    1    3    0]
 [  29   12   32   11   22   38 1127    0    0    0]
 [   9   13   44   17   24    8    0 1172    2    9]
 [  19   29   63   72   26   71   15   13  926    3]
 [  14    7   13   32   77   32    2   49   19  995]]
             precision    recall  f1-score   support

          0       0.90      0.99      0.94      1229
          1       0.92      0.98      0.95      1412
          2       0.82      0.93      0.87      1245
          3       0.81      0.92      0.86      1268
          4       0.86      0.94      0.90      1211
          5       0.85      0.82      0.84      1189
          6       0.97      0.89      0.93      1271
          7       0.93   

In [27]:
metrics.accuracy_score(y_test,pred_model)

0.8942857142857142

In [28]:
# for bagging
from sklearn.ensemble import BaggingClassifier

In [29]:
bagg = BaggingClassifier(n_estimators=5,bootstrap=True, oob_score=True)

In [30]:
bagg_model = bagg.fit(x_train,y_train)


C:\Users\AKSHAY\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:605: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\AKSHAY\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])


In [32]:
pred_bagg = bagg_model.predict(x_test)

In [34]:
metrics.accuracy_score(y_test,pred_bagg)

0.901984126984127

In [35]:
# Averaging the scores
dtree_prob = dtree.predict_proba(x_test)
rf_prob = rf.predict_proba(x_test)

In [37]:
scores_prob = (dtree_prob+rf_prob)/2


In [38]:
# for boosting
from sklearn.ensemble import AdaBoostClassifier

In [47]:
boost = AdaBoostClassifier(dtree,n_estimators=20,learning_rate=1.0,random_state=123)

In [48]:
boost_model = boost.fit(x_train,y_train)

In [49]:
pred_boost = boost_model.predict(x_test)

In [50]:
metrics.accuracy_score(y_test,pred_boost)

0.8523809523809524