# NumPy Lab Exercises 

Solve the following questions

#### Import NumPy package as np

In [1]:
import numpy as np

#### Create an empty array of 20 0's and replace the 4th object with the number 5

In [15]:
sample_array2 = np.zeros(20)
sample_array2[5]=5
sample_array2

array([0., 0., 0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 20 1's and store it as a variable named array_master. Copy the same array into another variable named array_copy

In [6]:
array_master = np.ones(20)
array_copy = array_master
array_copy


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

#### Create an array containing 30 1's and broadcast all the one's to the value 100

In [10]:
sample_array1 = np.ones(30)
sample_array1[:]=100
sample_array1


array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

#### Create an array of integers starting from 21 until 31 and name it as array1

#### Create an array of integers starting from 11 until 21 and name it array2

#### Calculate the difference between array1 and array2

In [21]:
array_1 = np.arange(21,31)
array_2 = np.arange(11,21)
array_1-array_2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

#### Create an array of all even integers from 2 to 10 and name it a1

#### Create an array of all even integers from 22 to 30 and name it a2

####  a) Use the 2 arrays as rows and create a matrix [ Hint - Use stack function from numpy ]

In [42]:
array_1 = np.arange(2,10,2)
array_2 = np.arange(22,30,2)

matrix = np.stack((array_1,array_2),axis=-1)
matrix


                  


array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28]])

####  b) Use the 2 arrays as columns and create a matrix [ Hint - Use column_stack function from numpy ]

In [45]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

#### Create a 5x6 matrix with values ranging from 0 to 29 and retrieve the value intersecting at 2nd row and 3rd column

In [50]:
sample_matrix = np.array(([50,200,5,10,20],[10,35,50,15,15],[25,100,145,120,120],[105,25,65,80,150],[13,17,19,21,23]))
sample_matrix[2,3]

120

#### Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [51]:
np.eye(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

#### Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [53]:
simple_array = np.random.randn(10)
simple_array>.2

array([False,  True,  True,  True, False, False, False,  True, False,
        True])

#### Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

array([[ 0.76925765, -0.36664186],
       [-0.05539837, -1.36852521],
       [-2.48454523, -1.28592728],
       [ 0.51083911, -0.86420807],
       [-1.49976158,  0.56103237]])

#### Create an array of 30 linearly spaced points between 0 and 100:

In [54]:
np.linspace(0,30,100)

array([ 0.        ,  0.3030303 ,  0.60606061,  0.90909091,  1.21212121,
        1.51515152,  1.81818182,  2.12121212,  2.42424242,  2.72727273,
        3.03030303,  3.33333333,  3.63636364,  3.93939394,  4.24242424,
        4.54545455,  4.84848485,  5.15151515,  5.45454545,  5.75757576,
        6.06060606,  6.36363636,  6.66666667,  6.96969697,  7.27272727,
        7.57575758,  7.87878788,  8.18181818,  8.48484848,  8.78787879,
        9.09090909,  9.39393939,  9.6969697 , 10.        , 10.3030303 ,
       10.60606061, 10.90909091, 11.21212121, 11.51515152, 11.81818182,
       12.12121212, 12.42424242, 12.72727273, 13.03030303, 13.33333333,
       13.63636364, 13.93939394, 14.24242424, 14.54545455, 14.84848485,
       15.15151515, 15.45454545, 15.75757576, 16.06060606, 16.36363636,
       16.66666667, 16.96969697, 17.27272727, 17.57575758, 17.87878788,
       18.18181818, 18.48484848, 18.78787879, 19.09090909, 19.39393939,
       19.6969697 , 20.        , 20.3030303 , 20.60606061, 20.90

## Numpy Indexing and Selections

Using the below given Matrix, generate the output for the below questions

In [57]:
simple_matrix = np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [58]:
simple_matrix[8:,:3]

array([[81, 82, 83],
       [91, 92, 93]])

#### b) Retrieve the value 55 from the above matrix using index & selection technique

In [61]:
simple_matrix[5][4]

55

#### c) Retrieve the values from the 3rd column in the above matrix

In [63]:
simple_matrix[:,3]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

#### d) Retrieve the values from the 4th row in the above matrix

In [64]:
simple_matrix[4,:]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

#### e) Retrieve values from the 2nd & 4th rows in the above matrix

In [66]:
simple_matrix[2:,4]

array([25, 35, 45, 55, 65, 75, 85, 95])

### Calculate the following values for the given matrix

#### a) Calculate sum of all the values in the matrix

In [68]:
np.mean(simple_matrix)

50.5

#### b) Calculate standard deviation of all the values in the matrix

In [67]:
np.std(simple_matrix)

28.86607004772212

#### c) Calculate the variance of all values in the matrix

In [69]:
np.var(simple_matrix)

833.25

#### d) Calculate the mean of all values in the matrix

In [70]:
np.mean(simple_matrix)

50.5

#### e) Retrieve the largest number from the matrix

In [71]:
np.max(simple_matrix)

100

#### f) Retrieve the smallest number from the matrix

In [72]:
np.min(simple_matrix)

1

### End of Lab Exercise - NumPy